/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  typescriptSidebar: [
    {
      type: 'category',
      label: 'JS eco-system',
      items: [
        {
          type: 'category',
          label: 'Introduction ✨',
          link: { id: 'js-es/intro', type: 'doc' },
          items: [],
        
        },
        {
          type: 'category',
          label: 'Foundations 🪢',
          collapsed: true,
          collapsible: true,
          link: {
            type: 'doc',
            id: 'js-es/foundations/intro', 
          },
          items: [
            { type: 'doc', id: 'js-es/foundations/compiler', label: 'Compiler Definition 🏷' },
            { type: 'doc', id: 'js-es/foundations/transpiler', label: 'Transpiler Definition 🏷' },
            { type: 'doc', id: 'js-es/foundations/environment', label: 'Environment Definition 🏷' },
            { type: 'doc', id: 'js-es/foundations/naive-build', label: 'Naive Build Definition 🏷' },
            { type: 'doc', id: 'js-es/foundations/incremental-build', label: 'Incremental Build Definition 🏷' },
            { 
              type: 'category', label: 'Modules 🧩', items: [
                { type: 'doc', id: 'js-es/foundations/modules/summary', label: 'Module Systems Summary' },
                { type: 'doc', id: 'js-es/foundations/modules/modules-compatibility', label: 'Environments Modules Compatibility 📊' },
                { type: 'doc', id: 'js-es/foundations/modules/esm', label: 'ES Module System Definition 🏷' },
                { type: 'doc', id: 'js-es/foundations/modules/umd', label: 'UMD Module System Definition 🏷' },
                { type: 'doc', id: 'js-es/foundations/modules/amd', label: 'AMD Module System Definition 🏷' },
                { type: 'doc', id: 'js-es/foundations/modules/commonjs', label: 'CommonJS Module System Definition 🏷' },
                { type: 'doc', id: 'js-es/foundations/modules/raw', label: 'Raw <script> Definition 🏷' },
                { type: 'doc', id: 'js-es/foundations/modules/modules-bundler', label: 'Modules Bundler Definition 🏷' },
                { type: 'doc', id: 'js-es/foundations/modules/nodejs-modules-support', label: 'Node.js - Modules Support 🏷' }
              ],  
            }
          ]
        },
        {
          type: 'category', 
          label: 'TypeScript', 
          link: {
            id: 'js-es/typescript/intro',
            type: 'doc',
          },
          items: [
            {
              type: 'category',
              label: 'Optimizations ⚡️',
              link: { 
                id: 'js-es/typescript/optimizations/intro',
                type: 'doc',
              },
              items: [
                { type: 'doc', id: 'js-es/typescript/optimizations/incremental-build', label: 'TS Incremental build 🧱' },
                { type: 'doc', id: 'js-es/typescript/optimizations/project-references', label: 'Project References (Composite Projects)' },
                { type: 'doc', id: 'js-es/typescript/optimizations/project-references-explained/intro', label: 'Project References 🧬' },
                { type: 'doc', id: 'js-es/typescript/optimizations/import-helpers', label: 'Import Helpers 🧿' },
              ]
            },
          ] 
        },
        {
          type: 'category',
          label: 'Testing Frameworks',
          items: [
            {
              type: 'category',
              label: 'Jest 🤡',
              link: { type: 'doc', id: 'js-es/testing-frameworks/jest/intro' },
              items: [
                {
                  type: 'category',
                  label: 'Mocks 🃏',
                  link: {id: 'js-es/testing-frameworks/jest/mocks/intro', type: 'doc' },
                  items: [
                    {
                      id: 'js-es/testing-frameworks/jest/mocks/jest-do-mock',
                      type: 'doc',
                      label: 'jest.doMock(🤡)'
                    }
                  ]
                },
                {
                  type: 'category',
                  label: 'Jest Architecture Series 🏛',
                  link: { type: 'doc' , id: 'js-es/testing-frameworks/jest/architecture/intro' },
                  items: [
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/intro', 
                      label: 'Introduction ✨'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/the-complete-architecture', 
                      label: 'The Complete Architecture Diagram 🏛'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/part-1-configs', 
                      label: 'P1: Configs 🧰'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/part-2-dependency-resolutions', 
                      label: 'P2: File System & Dependency Resolution 🌳'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/part-3-test-run-order', 
                      label: 'P3: Test Run Order (Optimizations) ⏳'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/part-4-test-run', 
                      label: 'P4: Test Run 🃏'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/part-5-the-runtime-environment', 
                      label: 'P5: The Runtime Environment 💽'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/part-6-modules-transformation', 
                      label: 'P6: Module Transformation 🦠'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/appendix-1-hoisting', 
                      label: 'Appx. Ⅰ: Jest Hoisting 🆙'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/appendix-2-jest-worker', 
                      label: 'Appx. Ⅱ: jest-worker 👷‍♂️'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/appendix-3-cache-summary', 
                      label: 'Appx. Ⅲ: Cache Summary 🏴‍☠️ (Coming soon...)'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/appendix-4-reporters', 
                      label: 'Appx. Ⅳ: Reporters 🚓 (Coming soon..)'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/appendix-5-watch-mode', 
                      label: 'Appx. Ⅴ: Watch Mode ⏱'
                    },
                    {
                      type: 'doc',
                      id: 'js-es/testing-frameworks/jest/architecture/appendix-6-frameworks-evolution', 
                      label: 'Appx. Ⅵ: Framework Evolution 🦕'
                    },
                  ]
                }
              ]
            }
          ]
        }
      ],
    },
    {
      'type': 'category',
      label: 'Testing',
      items: [
        {
          type: 'category',
          label: 'Unit Tests',
          link: {
            id: 'testing/unit/intro',
            type: 'doc',
          },
          items: [
            {
              type: 'category',
              label: 'Theory 🔭',
              link: { type: 'doc', id: 'testing/unit/theory/intro' },
              items: [
                {
                  id: 'testing/unit/theory/pros',
                  type: 'doc',
                  label: 'Pros 👍'
                },
                {
                  id: 'testing/unit/theory/cons',
                  type: 'doc',
                  label: 'Cons 👎'
                },
                {
                  id: 'testing/unit/theory/production-code-to-test-code-ratio',
                  type: 'doc',
                  label: 'Production/Test Code Ratio ☯'
                },
                {
                  id: 'testing/unit/theory/verify-test-code',
                  type: 'doc',
                  label: 'Verify Test Code ✅'
                },
                {
                  type: 'category',
                  label: 'Low-Effort/High-Value Cases 🤩',
                  link: { type: 'doc', id: 'testing/unit/theory/low-effort-high-value-cases/intro' },
                  items: [
                    {
                      id: 'testing/unit/theory/low-effort-high-value-cases/the-entry-module',
                      type: 'doc',
                      label: 'The Entry Module 🧭'
                    },
                    {
                      id: 'testing/unit/theory/low-effort-high-value-cases/data-transform',
                      type: 'doc',
                      label: 'Data Transform 🧭'
                    },
                    {
                      id: 'testing/unit/theory/low-effort-high-value-cases/conditional-validation',
                      type: 'doc',
                      label: 'Conditional Validation 🧭'
                    }
                  ]
                }
              ]
            }
          ],
        }
      ],
    }

  ],
  unitTestsSideBar: [

  ]
};

module.exports = sidebars;
