/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  typescriptSidebar: [
    {
      type: 'category', 
      label: 'TypeScript', 
      items: [
        {
          type: 'doc',
          id: 'typescript/index',
          label: 'Introduction ✨',
        },
        {
          type: 'category',
          label: 'Glossary 📚',
          collapsed: true,
          collapsible: true,
          link: { 
            // slug: 'typescript/glossary',
            type: 'doc',
            id: 'typescript/glossary/index', 
            // title: 'TypeScript Glossary 📚',
            // description: "All fundamental terms that simplify TypeScript!",
            // keywords: ['guides'], 
          },
          // link: { type: 'doc', id: 'typescript/glossary/index' },
          items: [
            // 'typescript/glossary/index',
            { type: 'doc', id: 'typescript/glossary/compiler-vs-transpiler' },
            { type: 'doc', id: 'typescript/glossary/js-module-systems-compatibility' },
            { type: 'doc', id: 'typescript/glossary/javascript-module-systems-explained' },
            { type: 'doc', id: 'typescript/glossary/bundlers-and-the-isomorphic-code-confusion', label: 'Isomorphic Code Confusion 🔮' },
            { type: 'doc', id: 'typescript/glossary/incremental-vs-naive-build' },
          ]
        },
        {
          type: 'category',
          label: 'Optimizations ⚡️',
          link: { 
            // slug: 'typescript/optimizations',
            // title: 'TypeScript Optimizations ⚡️',
            id: 'typescript/optimizations/index',
            type: 'doc',
            // description: `As the TypeScript eco-system becomes more mature, and many TypeScript projects gets bigger, especially in the monorepo era, Optimizations for your TypeScript project becomes more relevant than ever.
            // All the articles here unlock you crucial optimization that can be made for your project.`
          },
          items: [
            // { type: 'doc', id: 'typescript/optimizations/index', label: 'Introduction ✨'},
            { type: 'doc', id: 'typescript/optimizations/incremental-builds', label: 'TS Incremental builds 🧱' },
            { type: 'doc', id: 'typescript/optimizations/project-references-explained/index', label: 'Project References 🧬' },
            { type: 'doc', id: 'typescript/optimizations/import-helpers-with-tslib', label: 'Import Helpers 🧿' },
          ]
        },
        {
          type: 'category',
          label: 'Common Bugs Solved 🐞',
          link: { type: 'doc', id: 'typescript/bugs-solved/index' },
          items: [
            {
              id: 'typescript/bugs-solved/typescript-jest-cannot-use-import-statement-outside-module',
              type: 'doc',
              label: 'ts-jest: "Cannot use import statement outside module" 🤡'
            }
          ]
        }
      ] 
    }
  ],
};

module.exports = sidebars;
